#ifndef JUICY_USER_H_INCLUDED
#define JUICY_USER_H_INCLUDED


// User-editable Settings

// externalize these!!
// Kaiser2D
/*#define GAME_UI_BACKGROUND_COLOR 0x608588ff
#define GAME_UI_BUTTON_COLOR 0x8a5639ff
#define GAME_UI_BUTTON_COLOR_HOVER 0x946043ff
#define GAME_UI_BUTTON_COLOR_PRESSED 0x804c2fff
#define GAME_UI_BUTTON_FRAME_COLOR 0xffffffff
#define GAME_UI_BUTTON_FRAME_COLOR_HOVER 0xffff00ff
#define GAME_UI_BUTTON_FRAME_COLOR_PRESSED 0xdfdf00ff
#define GAME_UI_BUTTON_FONT_COLOR 0xffffffff
#define GAME_UI_BUTTON_FONT_COLOR_HOVER 0xffff00ff
#define GAME_UI_BUTTON_FONT_COLOR_PRESSED 0xdfdf00ff
#define GAME_UI_BUTTON_FRAME_SIZE 2
#define GAME_UI_FONT_TYPE "font.ttf"
#define GAME_UI_FONT_COLOR 0xffff00ff
#define GAME_UI_FONT_SIZE 16*/

// Packet Simulator
/*#define GAME_UI_BACKGROUND_COLOR 0x608588ff
#define GAME_UI_BUTTON_COLOR 0xba995cff
#define GAME_UI_BUTTON_COLOR_HOVER 0xcaa96cff
#define GAME_UI_BUTTON_COLOR_PRESSED 0xaa894cff
#define GAME_UI_BUTTON_FRAME_COLOR 0x000000ff
#define GAME_UI_BUTTON_FRAME_COLOR_HOVER 0x000000ff
#define GAME_UI_BUTTON_FRAME_COLOR_PRESSED 0x000000ff
#define GAME_UI_BUTTON_FONT_COLOR 0xf0f0f0ff
#define GAME_UI_BUTTON_FONT_COLOR_HOVER 0xffffffff
#define GAME_UI_BUTTON_FONT_COLOR_PRESSED 0x000000ff
#define GAME_UI_BUTTON_FRAME_SIZE 2
#define GAME_UI_FONT_TYPE "font.ttf"
#define GAME_UI_FONT_COLOR 0xffff00ff
#define GAME_UI_FONT_SIZE 16*/


#endif // JUICY_USER_H_INCLUDED
