#ifndef JUICYGUI_DEFINITIONS_H_INCLUDED
#define JUICYGUI_DEFINITIONS_H_INCLUDED


// User-editable Settings
// Kaiser2D
/*#define GAME_UI_BACKGROUND_COLOR 0x608588ff
#define GAME_UI_BUTTON_COLOR 0x8a5639ff
#define GAME_UI_BUTTON_COLOR_HOVER 0x946043ff
#define GAME_UI_BUTTON_COLOR_PRESSED 0x804c2fff
#define GAME_UI_BUTTON_FRAME_COLOR 0xffffffff
#define GAME_UI_BUTTON_FRAME_COLOR_HOVER 0xffff00ff
#define GAME_UI_BUTTON_FRAME_COLOR_PRESSED 0xdfdf00ff
#define GAME_UI_BUTTON_FONT_COLOR 0xffffffff
#define GAME_UI_BUTTON_FONT_COLOR_HOVER 0xffff00ff
#define GAME_UI_BUTTON_FONT_COLOR_PRESSED 0xdfdf00ff
#define GAME_UI_BUTTON_FRAME_SIZE 2
#define GAME_UI_FONT_TYPE "font.ttf"
#define GAME_UI_FONT_COLOR 0xffff00ff
#define GAME_UI_FONT_SIZE 16*/

// Packet Simulator
#define GAME_UI_BACKGROUND_COLOR 0x608588ff
#define GAME_UI_BUTTON_COLOR 0xba995cff
#define GAME_UI_BUTTON_COLOR_HOVER 0xcaa96cff
#define GAME_UI_BUTTON_COLOR_PRESSED 0xaa894cff
#define GAME_UI_BUTTON_FRAME_COLOR 0x000000ff
#define GAME_UI_BUTTON_FRAME_COLOR_HOVER 0x000000ff
#define GAME_UI_BUTTON_FRAME_COLOR_PRESSED 0x000000ff
#define GAME_UI_BUTTON_FONT_COLOR 0xf0f0f0ff
#define GAME_UI_BUTTON_FONT_COLOR_HOVER 0xffffffff
#define GAME_UI_BUTTON_FONT_COLOR_PRESSED 0x000000ff
#define GAME_UI_BUTTON_FRAME_SIZE 2
#define GAME_UI_FONT_TYPE "font.ttf"
#define GAME_UI_FONT_COLOR 0xffff00ff
#define GAME_UI_FONT_SIZE 16


// Charset
#define JUICYGUI_CHARSET_MASK 0x000000ff
#define JUICYGUI_CHARSET_SIZE JUICYGUI_CHARSET_MASK + 1
#define JUICYGUI_CHARSET_MAX_LENGTH 1024
#define JUICYGUI_CHARSET_REFERENCE_HEIGHT 65 // 'A'
#define JUICYGUI_CHARSET_LINE_MARGIN_DIVISOR 8

#define JUICYGUI_CHARSET_CHARNUM_LOWERCASE_A 97
#define JUICYGUI_CHARSET_CHARNUM_LOWERCASE_X 120
#define JUICYGUI_CHARSET_CHARNUM_DIGIT_0 48
#define JUICYGUI_CHARSET_CHARNUM_HYPHEN 45
#define JUICYGUI_CHARSET_CHARNUM_INT_OFFSET JUICYGUI_CHARSET_CHARNUM_DIGIT_0
#define JUICYGUI_CHARSET_CHARNUM_HEX_OFFSET (JUICYGUI_CHARSET_CHARNUM_LOWERCASE_A - 10)

#define JUICYGUI_CHARSET_MAX_PRINTJOBS 0x4000

// Button
#define JUICYGUI_BUTTON_SUBTYPE_BASIC 0x00000000
#define JUICYGUI_BUTTON_SUBTYPE_IMAGE 0x00000002

#define JUICYGUI_BUTTON_NUM_STATES 3
#define JUICYGUI_BUTTON_TEXTURE_ID_NONE 0
#define JUICYGUI_BUTTON_TEXTURE_ID_HOVER 1
#define JUICYGUI_BUTTON_TEXTURE_ID_PRESSED 2
#define JUICYGUI_BUTTON_TEXTURE_ID_RELEASED JUICYGUI_BUTTON_TEXTURE_ID_HOVER

// Box
#define JUICYGUI_BOX_BORDER_SIZE 2

// GUI
#define JUICYGUI_ELEMENTFLAG_SHOW 0x00000001
#define JUICYGUI_ELEMENTFLAG_DISABLED 0x00000002
#define JUICYGUI_ELEMENTFLAG_INIT (JUICYGUI_ELEMENTFLAG_SHOW & ~JUICYGUI_ELEMENTFLAG_DISABLED)

#define JUICYGUI_ACTION_NONE 0x00000000
#define JUICYGUI_ACTION_HOVER 0x00000001
#define JUICYGUI_ACTION_PRESSED 0x00000002
#define JUICYGUI_ACTION_RELEASED 0x00000004
#define JUICYGUI_ACTION_RESIZE 0x00000008

#define JUICYGUI_LOWLVL_EMPTY_ID_NUM 0
#define JUICYGUI_LOWLVL_ROOT_ID_NUM 1
#define JUICYGUI_TYPE_ID_NONE 0x00
#define JUICYGUI_TYPE_ID_GUI 0x01
#define JUICYGUI_TYPE_ID_BUTTON 0x02
#define JUICYGUI_TYPE_ID_CHARSET 0x04
#define JUICYGUI_TYPE_ID_BOX 0x08

#define JUICYGUI_CONTROL_ID_LMB 0x00000001
#define JUICYGUI_CONTROL_ID_MMB 0x00000002
#define JUICYGUI_CONTROL_ID_RMB 0x00000004

#define JUICYGUI_LOWLVL_DEFAULT_SCREEN_ORIGIN_X 0
#define JUICYGUI_LOWLVL_DEFAULT_SCREEN_ORIGIN_Y 0
#define JUICYGUI_LOWLVL_EMPTY_POS_X 0
#define JUICYGUI_LOWLVL_EMPTY_POS_Y 0
#define JUICYGUI_LOWLVL_EMPTY_WIDTH 0
#define JUICYGUI_LOWLVL_EMPTY_HEIGHT 0
#define JUICYGUI_LOWLVL_DEPTH 32
#if SDL_BYTEORDER == SDL_LIL_ENDIAN
    #define JUICYGUI_LOWLVL_MASKR 0xff000000
    #define JUICYGUI_LOWLVL_MASKG 0x00ff0000
    #define JUICYGUI_LOWLVL_MASKB 0x0000ff00
    #define JUICYGUI_LOWLVL_MASKA 0x000000ff
#else
    #define JUICYGUI_LOWLVL_MASKR 0x000000ff
    #define JUICYGUI_LOWLVL_MASKG 0x0000ff00
    #define JUICYGUI_LOWLVL_MASKB 0x00ff0000
    #define JUICYGUI_LOWLVL_MASKA 0xff000000
#endif // SDL_Byteorder

#endif // JUICYGUI_DEFINITIONS_H_INCLUDED
