#ifndef JUICYGUI_DEFINITIONS_H_INCLUDED
#define JUICYGUI_DEFINITIONS_H_INCLUDED

#include "Juicy_User.h"

// defaults User Settings
#ifndef GAME_UI_BACKGROUND_COLOR
    #define GAME_UI_BACKGROUND_COLOR 0x000000ff
#endif
#ifndef GAME_UI_BUTTON_COLOR
    #define GAME_UI_BUTTON_COLOR 0x9f9f9fff
#endif
#ifndef GAME_UI_BUTTON_COLOR_HOVER
    #define GAME_UI_BUTTON_COLOR_HOVER 0xafafafff
#endif
#ifndef GAME_UI_BUTTON_COLOR_PRESSED
    #define GAME_UI_BUTTON_COLOR_PRESSED 0x8f8f8fff
#endif
#ifndef GAME_UI_BUTTON_FRAME_COLOR
    #define GAME_UI_BUTTON_FRAME_COLOR 0x2b2b2bff
#endif
#ifndef GAME_UI_BUTTON_FRAME_COLOR_HOVER
    #define GAME_UI_BUTTON_FRAME_COLOR_HOVER 0xffffffff
#endif
#ifndef GAME_UI_BUTTON_FRAME_COLOR_PRESSED
    #define GAME_UI_BUTTON_FRAME_COLOR_PRESSED 0x000000ff
#endif
#ifndef GAME_UI_BUTTON_FONT_COLOR
    #define GAME_UI_BUTTON_FONT_COLOR 0xfafafaff
#endif
#ifndef GAME_UI_BUTTON_FONT_COLOR_HOVER
    #define GAME_UI_BUTTON_FONT_COLOR_HOVER 0xfafafaff
#endif
#ifndef GAME_UI_BUTTON_FONT_COLOR_PRESSED
    #define GAME_UI_BUTTON_FONT_COLOR_PRESSED 0xfafafaff
#endif
#ifndef GAME_UI_BUTTON_FRAME_SIZE
    #define GAME_UI_BUTTON_FRAME_SIZE 1
#endif
#ifndef GAME_UI_FONT_TYPE
    #define GAME_UI_FONT_TYPE "font.ttf"
#endif
#ifndef GAME_UI_FONT_COLOR
    #define GAME_UI_FONT_COLOR 0xffffffff
#endif
#ifndef GAME_UI_FONT_SIZE
    #define GAME_UI_FONT_SIZE 16
#endif

// Charset
#define JUICYGUI_CHARSET_NUM_STYLES 5
#define JUICYGUI_CHARSET_STYLE_NORMAL 0x0
#define JUICYGUI_CHARSET_STYLE_BOLD 0x1
#define JUICYGUI_CHARSET_STYLE_ITALIC 0x2
#define JUICYGUI_CHARSET_STYLE_UNDERLINE 0x4
#define JUICYGUI_CHARSET_STYLE_STRIKETHROUGH 0x8

#define JUICYGUI_CHARSET_MASK 0x000000ff
#define JUICYGUI_CHARSET_SIZE (JUICYGUI_CHARSET_MASK + 1)
#define JUICYGUI_CHARSET_MAX_LENGTH 0x1000
#define JUICYGUI_CHARSET_REFERENCE_HEIGHT 65 // 'A'
#define JUICYGUI_CHARSET_LINE_MARGIN_DIVISOR 8

#define JUICYGUI_CHARSET_CHARNUM_LOWERCASE_A 97
#define JUICYGUI_CHARSET_CHARNUM_LOWERCASE_X 120
#define JUICYGUI_CHARSET_CHARNUM_DIGIT_0 48
#define JUICYGUI_CHARSET_CHARNUM_HYPHEN 45
#define JUICYGUI_CHARSET_CHARNUM_INT_OFFSET JUICYGUI_CHARSET_CHARNUM_DIGIT_0
#define JUICYGUI_CHARSET_CHARNUM_HEX_OFFSET (JUICYGUI_CHARSET_CHARNUM_LOWERCASE_A - 10)

// Button
#define JUICYGUI_BUTTON_FLAG_NORMAL 0x0
#define JUICYGUI_BUTTON_FLAG_IMAGE 0x1
#define JUICYGUI_BUTTON_FLAG_MASK_TYPE 0x1

// Box
#define JUICYGUI_BOX_BORDER_SIZE 1

// GUI
#define JUICYGUI_COLOR_MOD_PERIOD 4000
#define JUICYGUI_COLOR_MOD_MIN 63
#define JUICYGUI_COLOR_MOD_MAX 224

#define JUICYGUI_ELEMENTFLAG_SHOW 0x1
#define JUICYGUI_ELEMENTFLAG_DISABLED 0x2
#define JUICYGUI_ELEMENTFLAG_STATIC 0x4
#define JUICYGUI_ELEMENTFLAG_INIT (JUICYGUI_ELEMENTFLAG_SHOW & ~JUICYGUI_ELEMENTFLAG_DISABLED)

#define JUICYGUI_NUM_ACTION 5
#define JUICYGUI_ACTION_NONE 0x0
#define JUICYGUI_ACTION_HOVER 0x1
#define JUICYGUI_ACTION_PRESSED 0x2
#define JUICYGUI_ACTION_RELEASED 0x4
#define JUICYGUI_ACTION_RESIZE 0x8

#define JUICYGUI_ID JUICYGUI_LOWLVL_ROOT_ID_NUM
#define JUICYGUI_TYPE_ID_NONE 0x0
#define JUICYGUI_TYPE_ID_GUI 0x1
#define JUICYGUI_TYPE_ID_BUTTON 0x2
#define JUICYGUI_TYPE_ID_CHARSET 0x4
#define JUICYGUI_TYPE_ID_BOX 0x8
#define JUICYGUI_ID_STATIC_TYPES (JUICYGUI_TYPE_ID_BUTTON | JUICYGUI_TYPE_ID_BOX)

#define JUICYGUI_CONTROL_ID_LMB 0x1
#define JUICYGUI_CONTROL_ID_MMB 0x2
#define JUICYGUI_CONTROL_ID_RMB 0x4
#define JUICYGUI_CONTROL_ID_LMB_CLICKED 0x10
#define JUICYGUI_CONTROL_ID_MMB_CLICKED 0x20
#define JUICYGUI_CONTROL_ID_RMB_CLICKED 0x40
#define JUICYGUI_CONTROL_ID_LMB_RELEASED 0x100
#define JUICYGUI_CONTROL_ID_MMB_RELEASED 0x200
#define JUICYGUI_CONTROL_ID_RMB_RELEASED 0x400

#define JUICYGUI_FPS_UPDATE 250
#define JUICYGUI_LOWLVL_MS1000 1000

#define JUICYGUI_LOWLVL_EMPTY_ID_NUM 0
#define JUICYGUI_LOWLVL_ROOT_ID_NUM 1
#define JUICYGUI_LOWLVL_EMPTY_POS_X 0
#define JUICYGUI_LOWLVL_EMPTY_POS_Y 0
#define JUICYGUI_LOWLVL_EMPTY_WIDTH 0
#define JUICYGUI_LOWLVL_EMPTY_HEIGHT 0

#include "JDM.h"

#include "JEN.h"
#include "JSPR.h"

#include "JuicyGUI_Element.h"
#include "JuicyGUI.h"

#endif // JUICYGUI_DEFINITIONS_H_INCLUDED
